language: c
compiler:
  - gcc

env:
  - TARGET_BOX=LINUX64 BTYPE="BINARY=64"
  - TARGET_BOX=LINUX64 BTYPE="BINARY=64 USE_OPENMP=1"
  - TARGET_BOX=LINUX64 BTYPE="BINARY=64 INTERFACE64=1"
  - TARGET_BOX=LINUX32 BTYPE="BINARY=32"
  - TARGET_BOX=WIN64 BTYPE="BINARY=64 HOSTCC=gcc CC=x86_64-w64-mingw32-gcc FC=x86_64-w64-mingw32-gfortran"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq gfortran
 - if [[ "$TARGET_BOX" == "WIN64" ]]; then sudo apt-get install -qq binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 gfortran-mingw-w64-x86-64; fi
 - if [[ "$TARGET_BOX" == "LINUX32" ]]; then sudo apt-get install -qq  gcc-multilib gfortran-multilib; fi

script: make QUIET_MAKE=1 DYNAMIC_ARCH=1 TARGET=NEHALEM NUM_THREADS=32 $BTYPE

# whitelist
branches:
  only:
    - master
    - develop